### ISSUE TITLE
How to turn off walk to pokestops may i ask ?

### ISSUE THREAD

**Issue by Luc4z** [Spegeli/Pokemon-Go-Rocket-API#40]
its really slow things down , can you tell me where should i add "//" to stop it ?
i hate it

**Comment by Spegeli** [comment]
you will remove Pokestop Farming complete?

**Comment by CL24** [comment]
He's asking for teleports between stops instead of human walking i guess.

**Comment by Luc4z** [comment]
yes ,  the old version did , before walking mode appear , but if its hard to approve its fine , i can deal with 0.*-2 seconds delay , your bot is the best currently , hope it wont crash and im still testing

**Comment by Luc4z** [comment]
@Spegeli hope you can show how many EXP we got from wild pokemon , because im wondering its using curve ball or not tho

**Comment by Luc4z** [comment]
issue is this one is totally slow the bot tho
"We are within 40 meters of the target. Speeding down to 10 km/h to not pass the target."

**Comment by Luc4z** [comment]
and also pokemon flee alot , shouldnt use last coord , should only use default one

**Comment by Spegeli** [comment]
The Teleport logic is completly removed, so its no longer possible with my version of the bot.
the bot is using curveballs every time as i know.
Pokemon Flee has nothing to do with the bot. this happens sometimes to when you play your self on the phone.

yeah the "We are within 40 meters of the target. Speeding down to 10 km/h to not pass the target." think is knowen and i will take a look later the day what i can do ;-)

for staying near a place you can use the new MaxTravelDistanceInMeters option. Set it to 5-20 and he should stay in this range to the Long & latitude.
i already implanted a new pathing function which walks a path you generat via a file, i test this later and then make a small guide in the readme file.

currently i work between 12 and 18 hours daily on the bot and this since 4 days and every day we get lots of new features and i only have 1 head and 2 hands ^^

**Comment by Luc4z** [comment]
@Spegeli thanks for the answer !

currently issue is pokemon flee alot , i set range 1000m as default but i lost pokemon too much ,
hope you can fix it senpai ! evolve everytime i caught is very awesome stuff

**Comment by Spegeli** [comment]
there is no flee issue ^^ i catch ~150 pokemon per hour
