### ISSUE TITLE
bot transfered my 700cp eevee pokemon *im crying*

### ISSUE THREAD

**Issue by aapikz** [Spegeli/Pokemon-Go-Rocket-API#42]
u have no idea how hard to find 700cp evee.. wtf
i assume bot detects evee as family of vaproen because i had vapreon before... but i want to keep 700cp evee as well... but the bot transfered it like nothing *im crying*
edit:
my 670 dratini is gone as well because i have family of 1 dragonite wtf....... im done with this

**Comment by Brewfasa** [comment]
Are you sure he didnt just evolve it? Since its in the evolve list if you enabled that

**Comment by aapikz** [comment]
ofcourse not it is disable by default and I only evolve pidgey,weedle,caterpie for exp farm,

**Comment by Brewfasa** [comment]
Hmmm i dont know..

Maybe you had another eevee that was higher and he removed the lower dupe?
Or maybe you had IV over CP on and it found a higher IV eevee with lower CP and still removed the higher CP one over that?

Else i really wouldn't know.. I didnt have this issue

**Comment by aapikz** [comment]
i have KeepMinDuplicatePokemon 0.. i thought it will not keep duplicate .. but it literally wipe it all

**Comment by SewayK** [comment]
No wonder you  KeepMinDuplicatePokemon 0. You are literally keeping no duplicate pokemon?

**Comment by Spegeli** [comment]
rly? you set KeepMinDuplicatePokemon to 0 and then wondering when every pokemon gets transferd?

**Comment by aapikz** [comment]
i thought KeepMinDuplicatePokemon 0 means keep strongest 
and  KeepMinDuplicatePokemon 1 means leaves duplicate like 1 eeve and 1 eevee :(

**Comment by Spegeli** [comment]
Currently the Transfer Logic is:

Select all Pokemon which are not in Gym or marked as Favorite and CP < MinCP
Then checkse the NotToTransfer List.
then depending if prioritizeIVoverCP enabled or not it will do the descending order by CP or IV
and at the end keep the X amount highest/best you set via KeepMinDuplicatePokemon

It will only transfer 100% when you set the KeepMinDuplicatePokemon to 0. But then its your fail.

KeepMinIVPercentage is currently not implanted/working because he will keep the stupid stuff like pokemons with 10 CP.
