### ISSUE TITLE
Autorestart script will end up saving folders on Desktop

### ISSUE THREAD

**Issue by ZerGo0** [Spegeli/Pokemon-Go-Rocket-API#43]
I bot more then 1 account on my VPS and I have a autorestart script running to fix issues while I am sleeping but right now the bot is doing this: http://i.imgur.com/yrWV3Mi.png

It shouldn't do that and I dont know how to fix it... :S

Regards

**Comment by Spegeli** [comment]
hhmm...within of the last versions, i outsourced some files like the Excel CSV, the Pokemon Lists etc.
normal he should make this in: PokemonGo.RocketAPI.Console\bin\Debug\ Folders

dont know if this issues comes because of your restart script. but normaly the current version should be stable and do not crash.

**Comment by ZerGo0** [comment]
Script works again had to create a shortcut to all bots so that they use their own folder.
